name: Full Build


on:
  push:
    branches: [ "main", "feature/*" ]

jobs:
  build_application:
    name: Test Application
    runs-on: self-hosted
    defaults:
      run:
        working-directory: TestApp
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
  test_application:
    name: Test Application
    runs-on: self-hosted
    steps:
      - name: Test
        run: dotnet test --no-build --verbosity normal