name: Full Build

on:
  push:
    branches: [ "main", "feature/*" ]

defaults:
  run:
    working-directory: src

env:
  # Setting the required env flags
  config: Release
  dotnet_core_version: 6.0.x
  app_name: testapp
  package_source: github

jobs:
  build_application:
    name: Build Application
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          repository: matpadley/test-action
          ref: v1.0
          path: ./.github/actions/test-action
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{env.dotnet_core_version}}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration ${{env.config}}

  test_action:
    name: joke
    runs-on: self-hosted
    needs: [build_application]
    steps:
      - name: installpackages
        run: npm --prefix ../.github/actions/joke-action install
      - name: ha-ha
        uses: ./.github/actions/joke-action

  test_application:
    name: Test Application
    runs-on: self-hosted
    needs: [build_application]
    steps:
      - name: Test
        run: dotnet test --no-build --verbosity normal

  package_application:
    name: Package Application
    runs-on: self-hosted
    needs: [test_application]
    steps:
      - name: Package
        run: dotnet pack --configuration ${{env.config}}
      - name: Push Package
        run: dotnet nuget push ${{env.app_name}}/bin/${{env.config}}/${{env.app_name}}.1.0.0.nupkg --source ${{env.package_source}} --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
