name: Build and Test Application

# Split this apart to build and test, and use workflow

on:
  push:
    branches: 
      [ "feature/*", "bugfix/*", "hotfix/*" ]
  pull_request:
    branches:
      [ "develop" ]

env:
  configuration: Release
  dotnet_core_version: 6.0.x
  node_version: 16

defaults:
  run:
    working-directory: src

jobs:
  environment_setup:
    name: Checkout Source
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
          # always-auth: true
          # registry-url: registry-url-here

  scanning:
    name: Code Scanning
    runs-on: self-hosted
    needs: [environment_setup]
    steps:
      - name: Run ESLint
        working-directory: src/TestApp/ClientApp
        run: |
          npm install eslint@8.10.0
          npm install @microsoft/eslint-formatter-sarif@2.1.7
          npx eslint . --config .eslintrc.js --ext .js,.jsx,.ts,.tsx --format @microsoft/eslint-formatter-sarif --output-file eslint-results.sarif
        continue-on-error: true
      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ./src/TestApp/ClientApp/eslint-results.sarif
          wait-for-processing: true
  
  build_dotnet_app:
    name: Build and Test .NET Core Application
    runs-on: self-hosted
    needs: [scanning]
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.dotnet_core_version }}
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore -c ${{ env.configuration }}
      - name: Test
        run: dotnet test . --no-build --verbosity normal --collect "Code Coverage" --logger:"trx;LogFilePrefix=testResults"

  build_javascript:
    name: Build and Test Javascript Application
    runs-on: self-hosted
    needs: [scanning]
    steps:
      - name: Install Dependencies
        working-directory: src/TestApp/ClientApp
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
      - name: Build Application
        working-directory: src/TestApp/ClientApp
        run: npm run build
      - name: Run Tests
        working-directory: src/TestApp/ClientApp
        run: npm test