name: Build and Test

on:
  push:
    branches: 
      [ "feature/*", "bugfix/*", "hotfix/*" ]

defaults:
  run:
    working-directory: src

jobs:
  checkout_code:
    name: Checkout Source
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

  build_dotnet_app:
    name: Build and Test .NET Core Application
    runs-on: self-hosted
    needs: [checkout_code]
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
  
  test_javascript:
    name: Build and Test Javascript Application
    runs-on: self-hosted
    needs: [checkout_code]
    steps:
      # needs caching setting up
      - name: Install Dependencies
        working-directory: src/TestApp/ClientApp
        run: npm install
      - name: Build Application
        working-directory: src/TestApp/ClientApp
        run: npm run build
      - name: Run Tests
        working-directory: src/TestApp/ClientApp
        run: npm test