name: Containterise Application

              #type=ref,event=branch
              #type=sha
              #type=sha,prefix={{branch}}-
              #type=sha,format=long
              #type=sha,format=long,prefix={{branch}}-
on:
  push:
    branches: [ "develop" ]

defaults:
  run:
    working-directory: src

env:
  # Setting the required env flags
  config: Release
  dotnet_core_version: 6.0.x
  app_name: testapp
  package_source: github

jobs:
  push_to_docker:
    name: Push To Docker Application
    runs-on: self-hosted
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@69f6fc9d46f2f8bf0d5491e4aabe0bb8c6a4678a
        with:
          images: matp79/SastTest
          tags: 
              type=raw,value=latest
      
      - name: Build and push Docker image
        uses: docker/build-push-action@c84f38281176d4c9cdb1626ffafcd6b3911b5d94
        with:
          context: ./src
          push: true
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}