name: Deploy Pipeline

on:
  release:
    types: [created]

env:
  key_vault: matpinsight
  image_name: sasttest
  repo_name: matp79

jobs:
  testing:
    name: Deploy To Testing
    environment: 
      name: testing
      url: ${{ steps.deploy-to-testing.outputs.webapp-url }}
    runs-on: self-hosted
    steps:
      - uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURESECRET }}
      - uses: Azure/get-keyvault-secrets@v1
        with:
          keyvault: ${{ env.key_vault }} # name of key vault in Azure portal
          secrets: 'matpinsightghuser,matpinsightpassword'  # comma separated list of secret keys to fetch from key vault 
        id: githubsecrets # ID for secrets that you will reference

      - uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ steps.githubsecrets.outputs.matpinsightghuser }}
          password: ${{ steps.githubsecrets.outputs.matpinsightpassword }}
      - name: Tag For Testing
        run: |
          docker tag ${{ env.repo_name }}/${{ env.image_name }}:unstable ${{ env.repo_name }}/${{ env.image_name }}:test
          docker push ${{ env.repo_name }}/${{ env.image_name }}:test
      - name: Deploy Application  
        id: deploy-to-testing
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'SastTestContainer'
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}
          images: 'index.docker.io/${{ env.repo_name }}/${{ env.image_name }}:test'

#  uat:
#    needs: testing
#    name: Deploy To UAT
#    environment: uat
#    runs-on: self-hosted
#  production:
#    needs: uat
#    name: Deploy To Production
#    environment: production
#    runs-on: self-hosted