name: Deploy Pipeline

on:
  workflow_dispatch:

env:
  image_name: sasttest
  repo_name: matp79

jobs:
  testing:
    name: Deploy To Testing
    environment: 
      name: testing
      url: ${{ steps.deploy-to-testing.outputs.webapp-url }}
    runs-on: self-hosted
    steps:
      - name: Deploy Application
        id: deploy-to-testing
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'SastTestContainer'
          publish-profile: ${{ secrets.PUBLISH_PROFILE }}
          images: 'index.docker.io/${{ env.repo_name }}/${{ env.image_name }}:latest'
#  uat:
#    needs: testing
#    name: Deploy To UAT
#    environment: uat
#    runs-on: self-hosted
#  production:
#    needs: uat
#    name: Deploy To Production
#    environment: production
#    runs-on: self-hosted