name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./TestApp

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file TestApp/Dockerfile --tag my-image-name:$(date +%s)
