name: KV Test

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURESECRET }}
      - uses: Azure/get-keyvault-secrets@v1
        with:
          keyvault: "matpinsight" # name of key vault in Azure portal
          secrets: 'matpinsightghuser'  # comma separated list of secret keys to fetch from key vault 
        id: githubsecrets # ID for secrets that you will reference