name: Security Scan Application

on:
  push:
    branches: 
      [ "feature/*", "bugfix/*", "hotfix/*" ]
  pull_request:
    branches:
      [ "develop" ]

env:
  image_name: sasttest
  repo_name: matp79

jobs:
  environment_setup:
    runs-on: self-hosted
    name: Setup Scanning Envrionment
    steps:
      - run: echo 'SETUP'
      - run: echo 'image_vuln_scanning'
      - run: echo 'library_vuln_scanning'
      #- run: echo 'license_vuln_scanning'
      - run: echo 'container_vuln_scanning'
      #- run: echo 'code_style'
      #- run: echo 'static analysis'
      - run: echo 'on fail raise Jira ticket'