name: Security Scan Application

on:
  push:
    branches: 
      [ "develop", "test" ]
  schedule:
    - cron: '00 00 * * *

jobs:
  environment_setup:
    name: Setup Scanning Envrionment
    steps:
      - run: echo 'SETUP'
  # image vulnerability scanning
  image_vuln_scanning:
    needs: [environment_setup]
    steps:
      - run: echo 'image_vuln_scanning'
  # library vulnerability scanning
  library_vuln_scanning:
    needs: [environment_setup]
    steps:
      - run: echo 'library_vuln_scanning'
  # license scanning
  license_vuln_scanning:
    needs: [environment_setup]
    steps:
      - run: echo 'license_vuln_scanning'
  # container config scanning
  container_vuln_scanning:
    needs: [environment_setup]
    steps:
      - run: echo 'container_vuln_scanning'
  # code style
  code_style:
    needs: [environment_setup]
    steps:
      - run: echo 'code_style'
  # static analysis
  code_style:
    needs: [environment_setup]
    steps:
      - run: echo 'static analysis'