name: Security Scan Application

on:
  push:
    branches: 
      [ "feature/*", "bugfix/*", "hotfix/*" ]
  pull_request:
    branches:
      [ "develop" ]

jobs:
  environment_setup:
    runs-on: self-hosted
    if: github.event.pull_request.merged == 'true' || github.event_name == 'push'
    name: Setup Scanning Envrionment
    steps:
      - run: echo 'SETUP'
      - run: echo 'image_vuln_scanning'
      - run: echo 'library_vuln_scanning'
      - run: echo 'license_vuln_scanning'
      - run: echo 'container_vuln_scanning'
      - run: echo 'code_style'
      - run: echo 'static analysis'
      - run: echo 'on fail raise Jira ticket'