name: Security Scan Application

on:
  pull_request:
    branches: ["develop"]
    types:
      - closed
  workflow_dispatch:

jobs:
  environment_setup:
    runs-on: self-hosted
    if: github.event.pull_request.merged == 'true'
    name: Setup Scanning Envrionment
    steps:
      - run: echo 'SETUP'
      - run: echo 'image_vuln_scanning'
      - run: echo 'library_vuln_scanning'
      - run: echo 'license_vuln_scanning'
      - run: echo 'container_vuln_scanning'
      - run: echo 'code_style'
      - run: echo 'static analysis'
      - run: echo 'on fail raise Jira ticket'