name: Security Scan Application

on:
  #pull_request:
  #  branches: ["develop"]
  #  types:
  #    - closed
  push:
    branches: 
      [ "feature/*", "bugfix/*", "hotfix/*" ]

permissions:
  pull-requests: read 

jobs:
  environment_setup:
    if: github.event.pull_request.merged == true
    name: Setup Scanning Envrionment
    steps:
      - run: echo 'SETUP'
  # image vulnerability scanning
  image_vuln_scanning:
    needs: [environment_setup]
    steps:
      - run: echo 'image_vuln_scanning'
  # library vulnerability scanning
  library_vuln_scanning:
    needs: [environment_setup]
    steps:
      - run: echo 'library_vuln_scanning'
  # license scanning
  license_vuln_scanning:
    needs: [environment_setup]
    steps:
      - run: echo 'license_vuln_scanning'
  # container config scanning
  container_vuln_scanning:
    needs: [environment_setup]
    steps:
      - run: echo 'container_vuln_scanning'
  # code style
  code_style:
    needs: [environment_setup]
    steps:
      - run: echo 'code_style'
  # static analysis
  static_analysis:
    needs: [environment_setup]
    runs-on: self-hosted
    steps:
      - uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Generate a token on Sonarcloud.io, add it to the secrets of this repo with the name SONAR_TOKEN (Settings > Secrets > Actions > add new repository secret)
       