name: Snyk

on:
  push:
    branches: 
      [ "feature/*", bugfix/* ]
  pull_request:
    branches:
      [ "develop", "release" ]

defaults:
  run:
    working-directory: src

jobs:  
  setup:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - run: snyk auth ${{ secrets.SNYK_TOKEN }}
  run_tests:
    needs: [setup]
    runs-on: self-hosted
    steps:
      - run: snyk test --all-projects --sarif-file-output=../snyk.sarif
        continue-on-error: true 
  upload_results:
    needs: [run_tests]
    runs-on: self-hosted
    steps:
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif