name: Snyk

on:
  push:
    branches: 
      [ "feature/*", bugfix/* ]
  pull_request:
    branches:
      [ "develop", "release" ]

defaults:
  run:
    working-directory: src

jobs:  
  setup:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
  autheticate:
    runs-on: self-hosted
    steps:
      - run: snyk auth ${{ secrets.SNYK_TOKEN }}
  run_tests:
    runs-on: self-hosted
    steps:
      - run: snyk test --all-projects --sarif-file-output=../snyk.sarif
          continue-on-error: true 
  upload_results:
    runs-on: self-hosted
    steps:
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif


      #- name: Run Snyk to check for vulnerabilities
      #  uses: snyk/actions/dotnet@master
      #  env:
      #    SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      #  with:
      #- name: Upload result to GitHub Code Scanning
      #    args: --severity-threshold=high --sarif-file-output=snyk.sarif
      #  uses: github/codeql-action/upload-sarif@v2
      #  with:
      #    sarif_file: snyk.sarif