name: Snyk

on:
  push:
    branches: 
      [ "feature/*", bugfix/* ]
  pull_request:
    branches:
      [ "develop", "release" ]

defaults:
  run:
    working-directory: src

jobs:
  security:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - run: snyk test
      #- name: Run Snyk to check for vulnerabilities
      #  uses: snyk/actions/dotnet@master
      #  env:
      #    SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      #  with:
      #- name: Upload result to GitHub Code Scanning
      #    args: --severity-threshold=high --sarif-file-output=snyk.sarif
      #  uses: github/codeql-action/upload-sarif@v2
      #  with:
      #    sarif_file: snyk.sarif