name: Build and Test Application

on:
  push:
    branches: 
      [ "feature/*", bugfix/* ]
  pull_request:
    branches:
      [ "develop", "release" ]

defaults:
  run:
    working-directory: src

jobs:
  setup-environment:
    name: Setup
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore --configuration release
      - name: Test
        run: dotnet test . --no-build --verbosity normal 